name: &name my-xmonad
version: 0.2.0.0

dependencies:
  - X11 >= 1.10.3 && < 1.11
  - base >= 4.17.1.0 && < 4.18
  - containers >= 0.6.7 && < 0.6.8
  - directory >= 1.3.7.1 && < 1.4
  - filepath >= 1.4.2.2 && < 1.5
  - xmonad >= 0.17.2 && < 1.18
  - xmonad-contrib >= 0.17.1 && < 1.18

ghc-options: -Wall -Werror

default-extensions:
  - OverloadedStrings
  - FlexibleContexts
  - ScopedTypeVariables
  - LambdaCase

executables:
  xmonad:
    source-dirs: src
    main: Main.hs
